extensions:
  dx_genstudio/genstudiopem/1:
    $include: src/genstudiopem/ext.config.yaml
    runtimeManifest:
      packages:
        genstudio-aem-fragments-app:
          license: Apache-2.0
          actions:
            fragment-finder:
              function: src/genstudiopem/actions/fragment-finder/index.js
              web: 'yes'
              runtime: nodejs:22
              inputs:
                LOG_LEVEL: info
                CF_FOLDER_PATH: $CF_FOLDER_PATH  
              annotations:
                require-adobe-auth: false
                final: true
