extensions:
  dx_genstudio/genstudiopem/1:
    $include: src/genstudiopem/ext.config.yaml
    runtimeManifest:
      packages:
        genstudio-external-dam-app:
          license: Apache-2.0
          actions:
            search:
              function: src/genstudiopem/actions/external-dam/index.js
              web: "yes"
              runtime: nodejs:22
              inputs:
                LOG_LEVEL: debug
                actionType: search
                S3_BUCKET_NAME: $GS_S3_BUCKET_NAME
                AWS_REGION: $GS_AWS_REGION
                AWS_ACCESS_KEY_ID: $GS_AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $GS_AWS_SECRET_ACCESS_KEY
              annotations:
                require-adobe-auth: true
                final: false
            upload-and-get-url:
              function: src/genstudiopem/actions/aio-lib-files/upload-and-get-url.js
              web: "yes"
              runtime: nodejs:22
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: true
                final: false
