name: External Template App PR

on:
  pull_request:
    paths:
      - "genstudio-external-template-app/**"
  workflow_dispatch:

jobs:
  pr:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-external-template-app
      environment: |
        [
          "Genstudio Engineering 01 - genstudio-external-template-app - workspace Stage", 
          "GenStudio GA PAT04 - genstudio-external-template-app - workspace Stage",
          "GenStudio Internal - E2E Tests - genstudio-external-template-app - workspace Stage",
          "Genstudio - Engineering - genstudio-external-template-app - workspace Stage"
        ]
    secrets: inherit
